no log: Improve CI and add auto vaildator for backend

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -5,21 +5,26 @@ on:
     branches: [development]
     paths:
       - frontend/**
+      - bazarr/**
+      - libs/**
+      - bazarr.py
+      - requirements.txt
+      - dev-requirements.txt
       - .github/workflows/ci.yml
   pull_request:
     branches: [development]
 
+env:
+    UI_DIRECTORY: ./frontend
 
 jobs:
   Frontend:
     runs-on: ubuntu-latest
-    env:
-      ROOT_DIRECTORY: .
-      UI_DIRECTORY: ./frontend
-
     steps:
       - name: Checkout repository
         uses: actions/checkout@v2
+        with:
+          fetch-depth: 1
 
       - name: Cache node_modules
         uses: actions/cache@v2
@@ -46,16 +51,41 @@ jobs:
           name: "ui"
           path: "${{ env.UI_DIRECTORY }}/build"
 
+  Backend:
+    runs-on: ubuntu-latest
+    needs: Frontend
+
+    steps:
+      - name: Checkout repository
+        uses: actions/checkout@v2
+        with:
+          fetch-depth: 1
+
       - name: Set up Python 3.8
         uses: actions/setup-python@v2
         with:
           python-version: '3.8'
 
-      - name: Install Python dependencies
-        run: |
-          python -m pip install --upgrade pip
-          pip install -r '${{ env.ROOT_DIRECTORY }}/requirements.txt'
+      - name: Install UI
+        uses: actions/download-artifact@v2
+        with:
+          name: "ui"
+          path: "${{ env.UI_DIRECTORY }}/build"
 
-      - name: Test Bazarr execution
+      - name: Install Python dependencies
+        run: pip install -r requirements.txt
+
+      - name: Unit Tests
         run: |
-          bash '.github/scripts/build_test.sh'
+          python3 bazarr.py &
+          PID=$!
+          sleep 15
+          if kill -s 0 $PID
+          then
+            echo "**** Bazarr launch successful ****"
+            kill $PID
+            exit 0
+          else
+          echo "**** Bazarr launch failed ****"
+            exit 1
+          fi
